### ISSUE TITLE
Question/Feature request

### ISSUE THREAD

**Issue by Fernien** [edvler/check_mk_proxmox-qemu-backup#15]
Hey there,
i run a proxmox cluster with a couple machines. Not all of them need to be backed up. 
Since i have my Proxmox nodes grouped in a folder inside of checkmk i created a rule for this folder.
I tried the following settings but it either showed all as okay since they don't get checked (OK: disabled by plugin) or a lot of failed ones since i don't want them to be backed up and checked. 
Is the Plugin working as intended or did i misunderstood something?  
![vzdump-1](https://user-images.githubusercontent.com/28627530/108834698-c4c6ae80-75ce-11eb-98bd-ca7ffa41d244.png)
![vzdump2](https://user-images.githubusercontent.com/28627530/108835156-5df5c500-75cf-11eb-8d35-49743649a952.png)

I just want the ones checked which have a backup job (/etc/cron.d/vzdump)

**Comment by edvler** [comment]
You have to add the "Service labels" for which the parameters are defined.

Maybe it's easier to klick on the "Burger menu" on the specific service -> "Parameters for this Service" -> "Proxmox VM guest backup" -> "Create Description specific rule for:"
then the Service label will be filled automatically.
