### ISSUE TITLE
NameError: name 'check_info' is not defined

### ISSUE THREAD

**Issue by czKKill** [edvler/check_mk_proxmox-qemu-backup#5]
Hello,

I was trying out your plugin but noticed this error during the tests (using the latest version of check from GitHub):
```
$/usr/lib/check_mk_agent/local/proxmox_qemu_backup
Traceback (most recent call last):
  File "/usr/lib/check_mk_agent/local/proxmox_qemu_backup", line 207, in <module>
    'has_perfdata':              True,
NameError: name 'check_info' is not defined
```

Am I missing something?

**Comment by edvler** [comment]
Hello,

are you running the script on your proxmox server?
Where did you get this error?

**Comment by czKKill** [comment]
I've fixed the formatting of the output in previous comment so be more clear - I'm running it directly on Proxmox server (6.2), manually executing the script. I've checked also output of the cmk agent and I can't see the proxmox_qemu_backup part

**Comment by czKKill** [comment]
Well turns out I was using a wrong script on the client, all is working now, sorry...
