### ISSUE TITLE
Plugin crashes after Backup

### ISSUE THREAD

**Issue by weirerit** [edvler/check_mk_proxmox-qemu-backup#7]
Hy,
since we updated Proxmox to 6.2-10, the Plugin / Check crashes every day.
Output as attached is correct (i think).
[agent-output.log](https://github.com/edvler/check_mk_proxmox-qemu-backup/files/4951615/agent-output.log)
We use CheckMK version 1.6.0p13

**Comment by boospy** [comment]
Same here at myhomelab.

**Comment by edvler** [comment]
Hello! I
am releasing a new version in a few days! You can test it by replacing the extract several infos part in YOUR-SITE-PATH/local/share/check_mk/checks/proxmox_qemu_backup file.

```
            try:
                #extract several infos
                if line[offset+5] == 'vzdump':
                    if line[offset+3] + ' ' + line[offset+4] + ' ' + line[offset+5] + ' ' + line[offset+6] == 'INFO: creating vzdump archive':
                        file_created = line
                else:
                    if line[offset+3] + ' ' + line[offset+4] + ' ' + line[offset+5] == 'INFO: creating archive':
                        file_created = line

                if line[offset+3] + ' ' + line[offset+4] + ' ' + line[offset+5] + ' ' + line[offset+6] == 'INFO: archive file size:':
                    archive = line
```

**Comment by weirerit** [comment]
Hi,
i've replaced the lines - but there is the same issue.

**Comment by edvler** [comment]
Hi,

please try to install the new mkp from the release v1.1.1.

I've updated my Proxmox to 6.2-10 and it works for me.
https://github.com/edvler/check_mk_proxmox-qemu-backup/releases/tag/v1.1.1

Greets
Matthias

**Comment by weirerit** [comment]
Thanks, it works now!
